[project]
name = "Projet-7-OPC"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "imblearn>=0.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "mlflow>=2.19.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]

[requires]
python = ">=3.13"